apiVersion: v1
kind: Service

metadata:
  name: broker

spec:
  selector:
    app: broker

  ports:
    - name: producer
      port: 7000
      targetPort: producer

    - name: consumer
      port: 7001
      targetPort: consumer